default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: angrails_development

test:
  <<: *default
  database: angrails_test

production:
  <<: *default
  database: angrails_production
  username: angrails
  password: <%= ENV['ANGRAILS_DATABASE_PASSWORD'] %>
